### ISSUE TITLE
CounterServer结束leader进程，过段时间重启会一直刷日志

### ISSUE THREAD

**Issue by gumandy** [alipay/sofa-jraft#53]
> Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j2 ]
2019-03-19 11:35:54 [main] INFO  log:30 - Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j2 ]
2019-03-19 11:35:56 [main] INFO  FSMCallerImpl:188 - Starts FSMCaller successfully.
2019-03-19 11:35:56 [Jraft-FSMCaller-disruptor-0] INFO  StateMachineAdapter:79 - onConfigurationCommitted: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083
2019-03-19 11:35:56 [Jraft-FSMCaller-disruptor-0] INFO  SnapshotExecutorImpl:435 - Node <counter/127.0.0.1:8081> onSnapshotLoadDone, last_included_index: 1
last_included_term: 1
peers: "127.0.0.1:8081"
peers: "127.0.0.1:8082"
peers: "127.0.0.1:8083"

> 2019-03-19 11:35:56 [main] INFO  NodeImpl:793 - Node <counter/127.0.0.1:8081> init, term: 1, lastLogId: LogId [index=1, term=1], conf: 127.0.0.1:8081,127.0.0.1:8082,127.0.0.1:8083, old_conf: 
2019-03-19 11:35:57 [main] INFO  RaftGroupService:139 - Start the RaftGroupService successfully.
Started counter server at port:8081
2019-03-19 11:35:57 [Rpc-netty-server-worker-1-thread-1] WARN  RaftRpcServerFactory:263 - JRaft SET bolt.rpc.dispatch-msg-list-in-default-executor to be false for replicator pipeline optimistic.
2019-03-19 11:35:57 [counter/127.0.0.1:8081-AppendEntriesThread0] INFO  LocalRaftMetaStorage:121 - Save raft meta, path=/tmp/server1\raft_meta, term=2, votedFor=0.0.0.0:0, cost time=15 ms
2019-03-19 11:35:57 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1589 - Node <counter/127.0.0.1:8081> reject term_unmatched AppendEntriesRequest from 127.0.0.1:8082 in term 2 prevLogIndex 2 prevLogTerm 2 localPrevLogTerm 0 lastLogIndex 1 entriesSize 0
2019-03-19 11:35:57 [Jraft-FSMCaller-disruptor-0] INFO  StateMachineAdapter:89 - onStartFollowing: LeaderChangeContext [leaderId=127.0.0.1:8082, term=2, status=Status[ENEWLEADER<10011>: Raft node receives message from new leader with higher term.]]
2019-03-19 11:35:57 [Bolt-default-executor-6-thread-2] INFO  NodeImpl:2695 - Node <counter/127.0.0.1:8081> received InstallSnapshotRequest lastIncludedLogIndex 2 lastIncludedLogTerm 2 from 127.0.0.1:8082 when lastLogId=LogId [index=1, term=1]
2019-03-19 11:35:57 [Bolt-conn-event-executor-5-thread-1] INFO  ClientServiceConnectionEventProcessor:50 - Peer 127.0.0.1:8082 is connected
2019-03-19 11:35:57 [JRaft-Closure-Executor-1] INFO  LocalSnapshotStorage:167 - Deleting snapshot /tmp/server1\snapshot\temp
2019-03-19 11:35:57 [JRaft-Closure-Executor-1] ERROR Utils:138 - Fail to close
java.io.IOException
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotStorage.close(LocalSnapshotStorage.java:251) ~[classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:98) ~[classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:93) ~[classes/:?]
	at com.alipay.sofa.jraft.util.Utils.closeQuietly(Utils.java:135) [classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotCopier.internalCopy(LocalSnapshotCopier.java:113) [classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotCopier.startCopy(LocalSnapshotCopier.java:85) [classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotCopier$$Lambda$9/945205179.run(Unknown Source) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
2019-03-19 11:35:57 [Jraft-FSMCaller-disruptor-0] ERROR CounterStateMachine:124 - Raft error: %s
com.alipay.sofa.jraft.error.RaftException: ERROR_TYPE_SNAPSHOT
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:660) ~[classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.loadDownloadingSnapshot(SnapshotExecutorImpl.java:499) ~[classes/:?]
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.installSnapshot(SnapshotExecutorImpl.java:484) ~[classes/:?]
	at com.alipay.sofa.jraft.core.NodeImpl.handleInstallSnapshot(NodeImpl.java:2699) ~[classes/:?]
	at com.alipay.sofa.jraft.rpc.impl.core.InstallSnapshotRequestProcessor.processRequest0(InstallSnapshotRequestProcessor.java:51) ~[classes/:?]
	at com.alipay.sofa.jraft.rpc.impl.core.InstallSnapshotRequestProcessor.processRequest0(InstallSnapshotRequestProcessor.java:1) ~[classes/:?]
	at com.alipay.sofa.jraft.rpc.impl.core.NodeRequestProcessor.processRequest(NodeRequestProcessor.java:58) ~[classes/:?]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:53) ~[classes/:?]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:1) ~[classes/:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:224) ~[bolt-1.5.3.jar:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:145) ~[bolt-1.5.3.jar:?]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:366) ~[bolt-1.5.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
2019-03-19 11:35:57 [Jraft-FSMCaller-disruptor-0] WARN  NodeImpl:2014 - Node <counter/127.0.0.1:8081> got error=Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to sync writer]]
2019-03-19 11:35:57 [Jraft-FSMCaller-disruptor-0] INFO  StateMachineAdapter:84 - onStopFollowing: LeaderChangeContext [leaderId=127.0.0.1:8082, term=2, status=Status[EBADNODE<10009>: Raft node(leader or candidate) is in error.]]
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-6] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-7] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-8] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-9] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-10] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-11] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-12] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-13] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-14] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:58 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:58 [Bolt-default-executor-6-thread-15] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:59 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:59 [Bolt-default-executor-6-thread-16] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:59 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:59 [Bolt-default-executor-6-thread-17] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:59 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:59 [Bolt-default-executor-6-thread-18] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:59 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:59 [Bolt-default-executor-6-thread-19] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR
2019-03-19 11:35:59 [counter/127.0.0.1:8081-AppendEntriesThread0] WARN  NodeImpl:1540 - Node <counter/127.0.0.1:8081> is not in active state, current term 2
2019-03-19 11:35:59 [Bolt-default-executor-6-thread-20] WARN  NodeImpl:2663 - Node <counter/127.0.0.1:8081> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR

**Comment by fengjiachun** [comment]
你好，看日志可能是快照被损坏了，能不能说下你详细的操作步骤？我这边无法再现

**Comment by gumandy** [comment]
清空快照，顺序启动三个server，查看日志找到leader，把leader停掉，等待选举出新的leader，最后把刚刚停掉的server启动，就出现如上日志了，ps：三个server在同台windows

**Comment by fengjiachun** [comment]
额。。。你好，快照是不能手动清除的

**Comment by gumandy** [comment]
我把三个快照目录都删了再启动的集群，这跟一个新的集群有啥区别，中途又没动过快照

**Comment by fengjiachun** [comment]
重建集群要删除所有数据，不止快照

**Comment by fengjiachun** [comment]
snapshot是会截断日志的，你把快照删除了，日志也被截断了，raft 内部却不知道， 所以你需要把 raft meta 等数据都删了，才叫新集群

**Comment by gumandy** [comment]
> 重建集群要删除所有数据，不止快照
是的我把全部{dataPath} 目录都删了，就是个崭新的集群
{dataPath} {groupId} {serverId} {initConf}

**Comment by gumandy** [comment]
> snapshot是会截断日志的，你把快照删除了，日志也被截断了，raft 内部却不知道， 所以你需要把 raft meta 等数据都删了，才叫新集群

应该是我描述得有问题，我是把所有data目录都删了，确定是个崭新的集群

**Comment by fengjiachun** [comment]
@gumandy 我应该是看明白你的操作步骤了
1. 你先停掉 leader
2. 然后删除了所有数据（包括另外 2 个 follower）
3. 然后启动之前停掉的节点
4. 出现了上面的日志

如果是这样的操作流程的话，肯定是不行的，你删除没有停掉的节点的数据是不行的，没停掉的两个节点有内存状态，会认为磁盘数据还在
这不是崭新集群，崭新的集群是全部重启并删除数据

**Comment by gumandy** [comment]
> 的操作流程的话，肯定是不行的，你删除没有停掉的节点的数据是不行的

1、删掉所有数据
2、启动崭新集群
3、停掉leader
4、等待重新选举成功
5、启动刚刚停掉的server
仅仅是第一步删掉所有数据，其他时候都没动过数据

**Comment by fengjiachun** [comment]
我按照你的操作步骤没能再现问题，在你的机器上是能稳定再现的吗？
 我按照我上面说的步骤是能再现的

**Comment by gumandy** [comment]
@fengjiachun 我的机器上是稳定重现的

**Comment by gumandy** [comment]
@fengjiachun 刷日志前还报了两个异常，贴出来日志里有

**Comment by fengjiachun** [comment]
2019-03-19 11:35:57 [JRaft-Closure-Executor-1] INFO LocalSnapshotStorage:167 - Deleting snapshot /tmp/server1\snapshot\temp

我的系统是mac os， 你在windows中指定的 dataPath 是什么？

**Comment by fengjiachun** [comment]
在 windows 中 “/tmp/server1\” 这个目测是不行的

**Comment by gumandy** [comment]
@fengjiachun 系统win10
启动参数是/tmp/server1时稳定重现，但是初始启动能成功
启动参数是D:/tmp/server1时就没问题了

**Comment by gumandy** [comment]
@fengjiachun 能根据/tmp/server1创建快照，为什么不能根据/tmp/server1删除快照，QAQ

**Comment by fengjiachun** [comment]
恩 这个参数是目录，windows 肯定是不支持这个目录的，我们这边整个团队也没有一个 windows 电脑，所以写文档时没有对 windows 做周全的考虑，这个很抱歉

**Comment by fengjiachun** [comment]
> @fengjiachun 能根据/tmp/server1创建快照，为什么不能根据/tmp/server1删除快照，QAQ

创建快照目录时肯定就是失败的，不可能成成功创建快照

**Comment by gumandy** [comment]
@fengjiachun 实不相瞒还真创建成功了，而且给出的客户端还能正常跑起来，快照里也存了数据，不然我也不会有第一步删数据操作了

**Comment by fengjiachun** [comment]
windows 不会把  ”/tmp/server1“ 作为一个目录了吧？ 是这样的吗？

**Comment by fengjiachun** [comment]
先关闭了，我们近期会找台 windows 电脑，一次性尽量解决所有不兼容 windows 的问题
